### ISSUE TITLE
`UnknownParameter("CHARSET")` might be too strict for compatibility with some software

### ISSUE THREAD

**Issue by tniessen** [tmpfs/vcard4#16]
As mentioned in #14, I currently use `.replace(";CHARSET=UTF-8", "")` to work around the error message `UnknownParameter("CHARSET")` when calling `vcard4::parse()`.

My understanding is that RFC 6350 makes UTF-8 mandatory, and has removed the `CHARSET` parameter (Appendix A.2). The RFC still permits a mime type parameter `charset`, which must be set to UTF-8 if present.

It seems that some software still produces a `CHARSET` parameter that is always set to `UTF-8`, and for interoperability with those systems, I think it might be nice to only issue an error if `CHARSET` is not `UTF-8`.

That being said, having the parameter at all seems to be a violation of RFC 6350, so it's also perfectly reasonable if you decide to close this issue as working as intended @tmpfs :)

**Comment by tmpfs** [comment]
> It seems that some software still produces a CHARSET parameter that is always set to UTF-8, and for interoperability with those systems, I think it might be nice to only issue an error if CHARSET is not UTF-8.

Yeh, I think we can be more relaxed here for better interop, let's parse the `CHARSET` property and error if it's anything other than `UTF-8`.

Happy to take a PR if you want to contribute this?

**Comment by tniessen** [comment]
> Happy to take a PR if you want to contribute this?

I gave it a try: https://github.com/tmpfs/vcard4/pull/17
